version: '3.8'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      TZ: "Asia/Shanghai"
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: "3306"
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tg2em-bot

  db:
    image: mysql:5.7
    container_name: npm_db
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "1989hewei"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--max_connections=1000'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - tg2em-bot

  emlog:
    image: emlog:latest
    container_name: emlog
    volumes:
      - ./emlog:/var/www/html
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "tg2em"
      MYSQL_USER: "tg2em"
      MYSQL_PASSWORD: "1989hewei"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tg2em-bot

  scrape:
    image: tg2em:latest
    container_name: tg2em_scrape
    command: ["python", "scrape.py"]
    stdin_open: true
    tty: true
    volumes:
      - telegram-data:/app/session
      - ./logs:/app/logs
      - ./upload:/app/upload
    environment:
      TZ: "Asia/Shanghai"
      PYTHONUNBUFFERED: "1"
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "tg2em"
      MYSQL_USER: "tg2em"
      MYSQL_PASSWORD: "1989hewei"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tg2em-bot

  publish:
    image: tg2em:latest
    container_name: tg2em_publish
    command: ["python", "publish.py"]
    volumes:
      - telegram-data:/app/session
      - ./logs:/app/logs
      - ./upload:/app/upload
    environment:
      TZ: "Asia/Shanghai"
      PYTHONUNBUFFERED: "1"
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "tg2em"
      MYSQL_USER: "tg2em"
      MYSQL_PASSWORD: "1989hewei"
    depends_on:
      - scrape
    networks:
      - tg2em-bot

volumes:
  telegram-data:
  data:
  letsencrypt:
  mysql:

networks:
  tg2em-bot:
    driver: bridge
